Tweet-CRUD
kiibo382/backend-kadai pull request #2
Opened 2020-07-14 12:24 UTC by kiibo382

tweet　の　CRUD機能を追加した。

2020-07-15 02:22 UTC, kpppn commented
不要なファイルがたくさんアップロードされてしまっているのでgitignoreを使って管理対象から外してください

2020-07-21 11:29 UTC, kiibo382 commented
お気に入り機能を追加した。

2020-07-21 12:07 UTC, kiibo382 commented
gitignore　編集完了しました。

2020-07-22 03:35 UTC, kpppn requested changes

2020-07-22 03:35 UTC, kpppn commented on .gitignore
> +__pyache__
重複指定しているものは片方にしてください
djangoのプロジェクトで共同開発する際にどのファイルが不要でどのファイルが必要なのかもう一度考えてみてください

.gitignoreに追加しても元々追跡対象に含まれているファイルが勝手に追跡対象から外れることはありません
自ら削除する必要があるので調べて実施してみてください

2020-07-22 04:14 UTC, kiibo382 commented
いらないファイルは削除し、共同開発において必要なファイルは残しました。採点の程、お願い致します。

2020-07-22 04:17 UTC, kiibo382 commented on .gitignore
> +__pyache__
コメント致しました。ご確認の程、お願い致します。

2020-07-22 05:50 UTC, kpppn commented on .gitignore
> +__pyache__
1. djangoプロジェクトにおける.gitignoreの内容で参考にしたサイトを教えてください
2. gitですでに管理対象にしてしまったファイルを管理対象外にするために参考にしたサイトを教えてください

2020-07-22 05:59 UTC, kiibo382 commented on .gitignore
> +__pyache__
https://hackable.jp/posts/1087
１，２ともにこのサイトを参考にしました。

2020-07-22 06:04 UTC, kpppn commented on .gitignore
> +__pyache__
1に関してはそのサイトにはないようなんですがあってますか？

2020-07-22 06:14 UTC, kiibo382 commented on .gitignore
> +__pyache__
すみません。1についての内容を誤解しておりました。
https://d-policy.com/?p=779
https://d-policy.com/?p=759
この二つを見て、分かりやすいディレクトリ構成にしました。お願い致します。

2020-07-22 06:14 UTC, kiibo382 commented
何度も修正してすみません。採点お願い致します。

2020-07-22 06:35 UTC, kpppn commented
あとちょっと
accounts/__pycache__/__init__.cpython-37.pyc
accounts/__pycache__/apps.cpython-37.pyc

とかが管理対象のままになってるからそれはずそう

2020-07-22 06:43 UTC, kiibo382 commented
外しました。確認のほどお願いいたします。

2020-07-22 08:25 UTC, kpppn commented
このアプリケーションを私のローカル環境でも実行したいのですが、なにか手順が必要ならreadmeに記載してください

2020-07-22 08:57 UTC, kiibo382 commented
local_setting ファイルを追加しました。

2020-07-22 09:00 UTC, kiibo382 commented
README.md に追加しました。動作中に何か問題が発生した場合はご連絡ください。

2020-07-22 14:17 UTC, kiibo382 commented
リファクタリングしました。採点の程、お願い致します。

2020-07-27 11:46 UTC, kpppn requested changes
確認お願いします

2020-07-27 11:46 UTC, kpppn commented on .gitignore
> +twitterclone/__pycache__/
gitignoreの仕様として `__pycache__/` の記載があればこの２行は不要です

2020-07-27 11:46 UTC, kpppn commented on README.md
> +local_settings.py 中の　sercret_key を　settings.py に追加してください。
依存パッケージをインストールできるようにして欲しいです
https://pip.pypa.io/en/stable/reference/pip_freeze/

2020-07-27 11:46 UTC, kpppn commented on twitterclone/views.py
> +edit = EditView.as_view()
ここも

2020-07-27 11:46 UTC, kpppn commented on twitterclone/views.py
> +index = IndexView.as_view()
クラスベースビューを使用する時はurl.pyの方でviewオブジェクトを生成したほうが汎用的で一般的だと思います

2020-07-27 11:46 UTC, kpppn commented on twitterclone/views.py
> +detail = DetailView.as_view()
ここも

2020-07-27 11:46 UTC, kpppn commented on accounts/views.py
> +                  'requesting_follows': requesting_follows})
クラスベースビューを使えばもっと処理が見やすくできるので変更してみてください

2020-07-27 11:46 UTC, kpppn commented on accounts/views.py
> +def info(request, user_id):
これもクラスベースビューへ

2020-07-27 11:46 UTC, kpppn commented on twitterclone/views.py
> +def delete(request, post_id):
誰でも削除できる？

2020-07-27 11:46 UTC, kpppn commented on twitterclone/views.py
> +class EditView(UpdateView):
誰でも編集できる？

2020-07-27 13:54 UTC, kiibo382 commented on accounts/views.py
> +                  'requesting_follows': requesting_follows})
クラスベースビューに書き換えるとこのコードよりも多くなってしまうのですが、、

2020-07-27 22:38 UTC, kiibo382 commented
クラスベースビューに書き換えるとこのコードよりも多く、または同程度の量のコードになってしまいます。一つの画面上で複数モデルを扱い、かつ、フォローしたら表示しない、フォローリクエストを出したら表示しない、ブロックしたら表示しない、などの制約が多々あるためです。

2020-07-28 06:44 UTC, kpppn commented
ソースコード量ではなく、他者が理解しやすいコードという視点で考えてみてください

2020-07-28 09:08 UTC, kpppn commented on templates/accounts/profile.html
> +     {% for post in user %}
lenのエラー発生してるのここじゃない？

2020-07-28 10:44 UTC, kiibo382 commented on templates/accounts/profile.html
> +     {% for post in user %}
ありがとうございます！

2020-07-28 12:31 UTC, kiibo382 commented
修正しました。

2020-07-29 01:41 UTC, kiibo382 commented
再度修正しました。

2020-07-29 02:01 UTC, kiibo382 commented
再度修正しました。

2020-07-29 08:14 UTC, kpppn requested changes

2020-07-29 08:14 UTC, kpppn commented on accounts/views.py
>          return self.render_to_response(context)
テンプレートに渡すcontextデータは `get_context_data` メソッドを活用するとなおいいと思います
https://docs.djangoproject.com/ja/3.0/topics/class-based-views/generic-display/#adding-extra-context

2020-07-29 08:14 UTC, kpppn commented on accounts/views.py
> +        if request.method == 'POST':
このif文はどうして必要？

2020-07-29 08:19 UTC, kiibo382 commented on accounts/views.py
> +        if request.method == 'POST':
不必要でした。

2020-07-29 08:19 UTC, kiibo382 commented on accounts/views.py
> +        if request.method == 'POST':
修正したのでお願いします。

2020-07-29 08:24 UTC, kiibo382 commented on accounts/views.py
>          return self.render_to_response(context)
その点も踏まえて修正しました。

2020-07-29 08:45 UTC, kpppn commented on templates/base.html
> +                    <li><a href="{% url 'accounts:profile' pk=user.id %}" class="profile">Profile</a></li>
この遷移先は常にログインしているユーザーですか？

2020-07-29 08:46 UTC, kpppn commented on twitterclone/views.py
> +        messages.warning(request, 'いいねを取り消しました')
これはいつ表示されますか？

2020-07-29 08:47 UTC, kpppn commented on twitterclone/views.py
> +        messages.success(self.request, "保存しました")
これもいつ表示されますか？

2020-07-29 08:58 UTC, kpppn commented on accounts/views.py
> +           Block.objects.remove_block(user, self.request.user)
それぞれ別のビューで実装してください

2020-08-02 22:53 UTC, kiibo382 commented
改善しました。

2020-08-03 08:06 UTC, kpppn requested changes
確認お願いします

2020-08-03 08:06 UTC, kpppn commented on twitterclone/views.py
> +        messages.success(self.request, "保存しました")
これの確認おねがいします

2020-08-03 08:06 UTC, kpppn commented on accounts/views.py
> +    if request.method == 'POST':
デコレーターを活用してシンプルにしよう
https://docs.djangoproject.com/ja/3.0/topics/http/decorators/#allowed-http-methods

2020-08-03 08:06 UTC, kpppn commented on accounts/views.py
> +        if 'accept' in request.POST:
このifは必要ですか？

2020-08-03 08:06 UTC, kpppn commented on accounts/views.py
> +        login_user = self.request.user
ログインしていないユーザーがこの画面にアクセスしたらどうなりますか？

2020-08-03 09:07 UTC, kiibo382 commented
修正しました。確認の程、よろしくお願いします。

2020-08-03 09:11 UTC, kiibo382 commented
微調整しました。

2020-08-03 09:36 UTC, kiibo382 commented
コードをきれいにしました。

2020-08-04 06:34 UTC, kpppn commented on templates/accounts/profile.html
> +    {% if friends == False %}
他の箇所にもありますが、これは意図的にboolの比較をしていますか？

2020-08-04 06:34 UTC, kpppn commented on accounts/views.py
> +            pass
ここではどうしてtry文を使用して例外を握りつぶしているのか教えてください

2020-08-04 06:34 UTC, kpppn commented on accounts/views.py
> +            pass
ここではどうしてtry文を使用して例外を握りつぶしているのか教えてください

2020-08-04 06:59 UTC, kiibo382 commented on templates/accounts/profile.html
> +    {% if friends == False %}
はい

2020-08-04 07:00 UTC, kiibo382 commented on accounts/views.py
> +            pass
loginしている場合のみ変数に値を代入するためです。

2020-08-04 07:01 UTC, kiibo382 commented on accounts/views.py
> +            pass
loginしている場合のみ変数に値を代入するためです。

2020-08-04 07:30 UTC, kiibo382 commented
修正しました。

2020-08-04 07:32 UTC, kpppn commented on templates/accounts/profile.html
> +    {% if friends == False %}
理由を教えてください

2020-08-04 07:33 UTC, kiibo382 commented on accounts/views.py
> +            pass
この部分も含めて修正しました。

2020-08-04 07:33 UTC, kiibo382 commented on accounts/views.py
> +            pass
この部分も含めて修正しました。

2020-08-04 07:35 UTC, kpppn commented on accounts/views.py
> +            pass
loginをしてるかしていないかの条件分岐なのであればifが適当かと思いますがなぜ例外処理なんでしょうか

2020-08-04 07:46 UTC, kiibo382 commented on accounts/views.py
> +            pass
その通りです。if に変えました。

2020-08-04 07:47 UTC, kiibo382 commented on accounts/views.py
> +            pass
フォローしている場合にのみ値を入れるために
            ```
try:
                requesting_follows = FriendshipRequest.objects.get(to_user=display_user.id, from_user=login_user.id)
            except:
                pass
```
を用いました。

2020-08-04 07:53 UTC, kiibo382 commented on templates/accounts/profile.html
> +    {% if friends == False %}
フォローしている同士、、すみません、このfriendsの確認は必要ありません。

2020-08-04 07:54 UTC, kiibo382 commented on templates/accounts/profile.html
> +    {% if friends == False %}
修正しました。

2020-08-04 08:52 UTC, kpppn approved these changes
lgtm

2020-08-16 06:57 UTC, kiibo382 commented
いいね機能を非同期にしました。また、テストも作成しました。

2020-08-18 08:30 UTC, kpppn commented
コメントアウトしている不要なコードは削除してください

2020-08-18 08:45 UTC, kpppn requested changes
ひとまずコメントしました
profileページのテストケースはありますか？

2020-08-18 08:45 UTC, kpppn commented on accounts/tests/test_follow.py
> +        self.assertEqual(res.status_code, 200)
これはPOSTリクエストを投げてるだけでフォローリクエストする処理は通ってなくない？

2020-08-18 08:45 UTC, kpppn commented on twitterclone/tests/test_return_correct_html.py
> +        response=self.client.get('/post_new/')
postメソッドを使用したテストケースも作成してください

2020-08-18 08:45 UTC, kpppn commented on twitterclone/tests/test_return_correct_html.py
> +        response = self.client.get('/edit/1/')
これもpostメソッドを使用したテストケースを作成してください

2020-08-18 08:45 UTC, kpppn commented on twitterclone/tests/test_like.py
> +        self.assertEqual(res.status_code, 200)
いいねを取り消すテストケースも実装してください

2020-08-19 10:07 UTC, kiibo382 commented
修正いたしました。

2020-08-24 01:00 UTC, kiibo382 commented
一つ誤りがあったため修正しました。

2020-08-24 07:13 UTC, kpppn requested changes
確認ください

2020-08-24 07:13 UTC, kpppn commented on twitterclone/tests/test_return_correct_html.py
> +        self.assertTemplateUsed(response, 'twitterclone/post_new.html')
これは投稿が失敗したパターンかな？
成功したパターンもお願いします

2020-08-24 07:13 UTC, kpppn commented on twitterclone/tests/test_return_correct_html.py
> +        self.assertTemplateUsed(response, 'twitterclone/edit.html')
こちらも失敗したパターンだけでなく成功したパターンもお願いします

2020-08-24 07:13 UTC, kpppn commented on accounts/tests/test_follow.py
> +        self.assertTrue(FriendshipRequest.objects.get(to_user=other_user.id))
テストコードの中でフォロー実行してもテストの意味ないですよ
実際のコードがテスト実施されてません

2020-08-24 07:46 UTC, kiibo382 commented on accounts/tests/test_follow.py
> +        self.assertTrue(FriendshipRequest.objects.get(to_user=other_user.id))
どういうことでしょうか？

2020-08-26 14:18 UTC, kiibo382 commented
修正しました。

2020-08-26 14:20 UTC, kiibo382 commented
コードを整えました。

2020-08-27 05:43 UTC, kpppn approved these changes
大枠いいのでおｋとします
以下は自分で確認しておいてください
- coverage.pyを使用してテストが実施できていない箇所の把握
- ひとつのメソッドで複数の期待値を含めてしまっているテストの分割
- テストに必要なテストデータを用意するためのsetupメソッドの活用

2020-08-27 10:40 UTC, merged